debug: true
bind: "localhost:8080"
admin: "admin"
password: "password"

db:
  type: "sqlite3"
  path: "./sqlite3.db"
  addr: "0.0.0.0:3306"
  user: "goldennum"
  password: "goldennum"
  db_name: "goldennum"
  redis:
  max_conns:
  max_idles:
  conn_life:
